openapi: 3.0.0
info:
  description: |
    This is the [Fireblocks](https://fireblocks.com) Exchange API standard.
    Check out the [API documentation](https://docs.fireblocks.com) for more information.
  title: Fireblocks Exchange API
  version: "0.3.0"
  contact:
    email: support@fireblocks.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/fb-api/Exchanges-API/1.0.0
  - url: 'https://api.fireblocks.com/v1'
  
paths:  
  /accounts:
    get:
      summary: Fetches list of all account types, and the balances within them
      operationId: getBalances
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                  $ref: '#/components/schemas/Balance'
        '401':
          description: Unauthorized. Either API details are missing or invalid
        '500':
          description: Exchange internal error, can't process this right now.

  /internalTransfer:
    post:
      summary: Initiate a transfer from one internal account to another, eg. TRADING to MARGIN
      operationId: internalTransfer
      parameters:
        - name: fromAccountType
          in: query
          description: "The sub-account type being transferred from."
          required: true
          example: "MARGIN"
          schema:
            $ref : '#/components/schemas/EAccountType'
        - name: toAccountType
          in: query
          description: "The sub-account type being transferred to."
          required: true
          example: "SPOT"
          schema:
            $ref : '#/components/schemas/EAccountType'
        - name: coinSymbol
          in: query
          example: "USDT"
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  completed:
                    type: boolean
                    example: true
                  transactionID:
                    type: string
                    description: "optional"
                    example: "3e8374383acce78d38be7fe9"
        '400':
          description: Invalid Operation
        '429':
          description: Rate limit reached
        
  /subaccountTransfer:
    post:
      summary: Initiate a transfer from one internal sub-account to another sub-account
      operationId: subaccountTransfer
      parameters:
        - name: subAccountID
          in: query
          required: true
          schema:
            type: string
        - name: direction
          in: query
          required: true
          description: "in: from another sub/main account, out: to another sub/main account"
          schema:
            type: string
            enum: [IN, OUT]
        - name: coinSymbol
          in: query
          required: true
          example: "USDT"
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  completed:
                    type: boolean
                    example: true
                  transactionID:
                    type: string
                    example: "3e8374383acce78d38be7fe9"
        '400':
          description: Invalid operation
        '429':
          description: Rate limit reached

  /withdraw:
    post:
      summary: Initiate a withdrawal from Exchange wallet to external wallet address
      operationId: withdraw
      parameters:
        - name: accountType
          in: query
          required: true
          schema:
            $ref : '#/components/schemas/EAccountType'
        - name: toAddress
          in: query
          required: true
          schema:
            type: string
        - name: tag
          in: query
          description: "(optional) A 'tag' or 'memo', if required by the network"
          schema:
            type: string
        - name: coinSymbol
          in: query
          required: true
          schema:
            type: string
        - name: network
          example: "ETH"
          in: query
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: string
        - name: isGross
          in: query
          required: true
          schema:
            type: boolean
        - name: maxFee
          in: query
          description: (optional) The service fee charged for withdrawal 
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionID:
                    type: string
                    example: "3e8374383acce78d38be7fe9"
        '400':
          description: Invalid operation
        '429':
          description: Rate limit reached

  /withdrawalFee:
    get:
      summary: Fetch the estimated transaction fee required for an external withdrawal
      operationId: fetchWithdrawalFee
      parameters:
        - name: transferAmount
          in: query
          required: true
          schema:
            type: string
        - name: coinSymbol
          in: query
          required: true
          schema:
            type: string
        - name: network
          example: "ETH"
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  feeAmount:
                    type: string
                    example: 0.23823
        '400':
          description: Invalid operation

  /depositAddress:
    get:
      summary: Fetch the deposit wallet address for a coinSymbol and network
      description: > 
        Fireblocks will first check if a deposit wallet address exists using this endpoint.
        If one does not exist, then a new address will be created using the `POST /depositAddress` endpoint.
      operationId: fetchDepositAddress
      parameters:
        - name: accountType
          in: query
          required: true
          example: "SPOT"
          schema:
            $ref : '#/components/schemas/EAccountType' 
        - name: coinSymbol
          in: query
          required: true
          example: "USDT"
          schema:
            type: string
        - name: network
          example: "ETH"
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  depositAddress:
                    type: string
                    example: "0xb794f5ea0ba39494ce839613fffba74279579268"
                  depositAddressTag:
                    type: string
                    description: "(optional) A destination tag/memo to include for supported coins eg. XLM, XRP etc.)"
                    example: "63163621"
        '400':
          description: Invalid operation
    post:
      summary: Create a new deposit wallet address for a given coinSymbol and network
      operationId: createDepositAddress
      parameters:
        - name: accountType
          in: query
          required: true
          schema:
            $ref : '#/components/schemas/EAccountType' 
        - name: coinSymbol
          in: query
          example: "USDT"
          required: true
          schema:
            type: string
        - name: network
          in: query
          example: "ETH"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  depositAddress:
                    type: string
                    example: "0xb794f5ea0ba39494ce839613fffba74279579268"
                  depositAddressTag:
                    type: string
                    description: "(optional) A destination tag/memo to include for supported coins eg. XLM, XRP etc.)"
                    example: "63163621"
        '400':
          description: Invalid operation

  /transactionStatus:
    get:
      summary: Fetch the status of a given transaction ID
      operationId: transactionStatus
      parameters:
        - name: transactionID
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionID:
                    type: string
                    example: "46bas218d9h21uhib4i1u2h"
                  status:
                    $ref: '#/components/schemas/Status'
                  txHash:
                    type: string
                    example: "44e25bc0ed840f9bf0e58d6227db15192d5b89e79ba4304da16b09703f68ceaf"
                  amount:
                    type: string
                    example: "1.1"
                  serviceFee:
                    type: string
                    example: "0.000000031"
                  coinSymbol:
                    type: string
                    example: "BTC"
                  network:
                    type: string
                    example: "BTC"
                  direction:
                    type: string
                    example: "DEPOSIT"
                    enum: [DEPOSIT, WITHDRAWAL]
                  timestamp:
                    type: string
                    format: UNIX-timestamp-epoch
                    example: "1649738389"
        '400':
          description: Invalid operation

  /transactionHistory:
    get:
      summary: Fetch the history of all transactions
      operationId: transactionHistory
      parameters:
        - name: fromDate
          in: query
          required: true
          schema:
            type: string
            format: UNIX-timestamp-epoch
            example: "1649738389"
        - name: toDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: pageSize
          in: query
          description: "Number of entries per page size in response"
          required: true
          schema:
            type: number
        - name: pageCursor
          in: query
          description: "(optional) If not specified, return the first page. Otherwise, return the page the cursor points to."
          schema:
            type: string
        - name: isSubTransfer
          in: query
          required: true
          example: false
          description: "If this is a sub-account tranfer"
          schema:
            type: boolean
        - name: coinSymbol
          in: query
          required: true
          example: "USDT"
          schema:
            type: string
        - name: network
          example: "ETH"
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nextPageCursor:
                        type: string
                        description: "(optional) If not present, refers to the last possible page. Otherwise refers to the next page."
                    transactions:
                      type: array
                      items:
                        type: object
                        properties:
                          transactionID:
                            type: string
                            example: "46bas218d9h21uhib4i1u2h"
                          status:
                            $ref: '#/components/schemas/Status'
                          txHash:
                            type: string
                            example: "44e25bc0ed840f9bf0e58d6227db15192d5b89e79ba4304da16b09703f68ceaf"
                          amount:
                            type: string
                            example: "1.1"
                          serviceFee:
                            type: string
                            example: "0.000000031"
                          coinSymbol:
                            type: string
                            example: "BTC"
                          network:
                            type: string
                            example: "BTC"
                          direction:
                            type: string
                            example: "DEPOSIT"
                            enum: [DEPOSIT, WITHDRAWAL]
                          timestamp:
                            type: string
                            format: UNIX-timestamp-epoch
                            example: "1649738389"
        '400':
          description: Invalid operation

  /supportedAssets:
    get:
      summary: Fetch the assets supported by the exchanges
      operationId: supportedAssets
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: object
                      properties:
                        coinSymbol:
                          type: string
                          example: "USDT"
                        network:
                          example: "ETH"
                          type: string
                        type:
                          type: string
                        contractAddress:
                          type: string
                          description: "(optional)"
        '400':
          description: Invalid operation

components:
  schemas:
    EAccountType:
      type: string
      description: "Enumeration on types of possible accounts"
      enum:
        - SPOT
        - FUNDING
        - FUTURES
        - MARGIN
      example:
        MARGIN
    Account:
      type: object
      properties:
        id:
          type: string
          example: "23e4567-e89b-12d3-a456-426614174000"
          description: "UUID representation of an account identifier"
        type:
          $ref : '#/components/schemas/EAccountType'
    AccountBalance:
      type: object
      properties:
        coinSymbol:
          type: string
          example: USDT
          description: "The symbol of the cryptocurrency"
        totalAmount:
          type: string
          example: 195.172612
          description: "The total amount (as a string, for precision) in the account"
        pendingAmount:
          type: number
          example: 188.2315812
          description: "The pending amount in usage, on mempool but not passed confirmations"
        availableAmount:
          type: number
          example: 10.333
          description: "The available amount for usage, the amount the account has with guarantee"
        borrowedAmount:
          type: number
          example: 3.1
          description: "The borrowed amount for usage, the amount the exchange borrowed to the user"
    Balance:
      type: object
      properties:
        type:
          $ref : '#/components/schemas/EAccountType'
        balances:
          type: array
          items:
            $ref: '#/components/schemas/AccountBalance'
    Status:
      type: string
      description: "Enumeration on types of possible statuses"
      enum:
        - NOT_FOUND
        - PROCESSING
        - CANCELLED
        - FAILED
        - PENDING_MANUAL_APPROVAL
        - PENDING_SERVICE_MANUAL_APPROVAL
        - REJECTED
        - COMPLETED
      example: "COMPLETED"

  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header